[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [executing] blocked: Insufficient permissions, try: `juju trust pgbouncer-k8s --scope=cluster`
[32mINFO    [0m pytest_operator.plugin:plugin.py:929 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.6.2    unsupported  01:34:48Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
pgbouncer-k8s        1.21.0   active      1  pgbouncer-k8s                       0  10.152.183.177  no       
postgresql-k8s       14.15    active      1  postgresql-k8s       14/edge      493  10.152.183.54   no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  344  10.152.183.140  no       received database credentials of the first database

Unit                    Workload  Agent  Address      Ports  Message
pgbouncer-k8s/0*        active    idle   10.1.213.9          
postgresql-k8s/0*       active    idle   10.1.213.11         Primary
postgresql-test-app/0*  active    idle   10.1.213.8          received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:935 Juju error logs:

unit-postgresql-k8s-0: 01:32:20 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata

[32mINFO    [0m pytest_operator.plugin:plugin.py:1017 Forgetting model main...