[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [executing] blocked: Insufficient permissions, try: `juju trust pgbouncer-k8s --scope=cluster`
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.6    unsupported  01:49:37Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
pgbouncer-k8s        1.21.0   active      1  pgbouncer-k8s                       0  10.152.183.215  no       
postgresql-k8s       14.13    active      1  postgresql-k8s       14/edge      431  10.152.183.204  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  275  10.152.183.76   no       received database credentials of the first database

Unit                    Workload  Agent  Address      Ports  Message
pgbouncer-k8s/0*        active    idle   10.1.64.137         
postgresql-k8s/0*       active    idle   10.1.64.139         Primary
postgresql-test-app/0*  active    idle   10.1.64.136         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

controller-0: 01:45:29 ERROR juju.worker.caasapplicationprovisioner.runner exited "postgresql-k8s": more than 20 retries ensuring scale: setting scale to 1 for "postgresql-k8s": statefulset "postgresql-k8s" not found
controller-0: 01:46:29 ERROR juju.worker.caasapplicationprovisioner.runner exited "postgresql-k8s": more than 20 retries ensuring scale: setting scale to 1 for "postgresql-k8s": statefulset "postgresql-k8s" not found

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...